### ISSUE TITLE
Appointment creation view 

### ISSUE THREAD

**Issue by Manuelgruiz** [ISPP-07/frontend-acat#19]
## Feature Description
Develop a feature to create an appointment registry that enables users to record details of appointments in a structured format.
## Motivation
This new appointment registry feature aims to streamline the process of documenting appointment information, enhancing organization and accessibility for users.
## Acceptance Criteria
- [ ] [Criteria 1: The appointment registry must allow users to input and store details an appointment.
- [ ] [Criteria 2: Each entry in the registry must include the date of the appointment.
- [ ] [Criteria 3: The name of the patient associated with each appointment must be included in the registry entry.
## Additional Details
The appointment registry should offer a user-friendly interface for inputting and viewing appointment details, ensuring ease of use and efficient management of appointment records.

**Comment by JaviGarc1a** [comment]
PR #21 is not merged
