### ISSUE TITLE
feat:Notifications

### ISSUE THREAD

**Issue by nicoloboo02** [ISPP-07/frontend-acat#79]
## Feature Description
Notification management to trigger notifications according to customer requirements
## Motivation
This is necessary to facilitate the handling of the application and updating by customers.
## Acceptance Criteria
- [ ] [Criteria 1: Notification view works]
- [ ] [Criteria 2: A number is displayed to the right of the icon showing the number of unseen notifications.]

**Comment by AntonioRodriguezRuiz** [comment]
This feature has been canceled

**Comment by TunixR** [comment]
This feature has been canceled
