### ISSUE TITLE
feat:Error handling

### ISSUE THREAD

**Issue by nicoloboo02** [ISPP-07/frontend-acat#80]
## Feature Description
All errors should be handled so that when the user gets an error, it is more descriptive.
## Acceptance Criteria
- [x] [Criteria 1: The errors are fully descriptive of why they jump out

**Comment by TunixR** [comment]
Validation for:
- Beneficiary create
- Beneficiary edit
- Login
- Intervention create
- Intervention edit
- User create
- User edit
